= Data synchronization in the JVM

== Introduction

_Data synchronization_ is the coordination between threads needed to ensure shared mutable data behaves according to desired specification.
Consider a JDBC connection pool, implemented as a list and shared by multiple threads. 
The access by multiple threads to this shared list must ensure proper data synchronization to ensure the list remains consistent, namely that no elements are lost or duplicated.
A way to achieve data synchronization  is via mutual exclusion.

_Control synchronization_ is also a form of coordination between threads, where threads need to wait for conditions that will 
be made true by other threads.
Using the same JDBC connection pool example, a thread getting a connection on an empty pool needs to wait for another thread to release a connection.
Note that it doesn't need to wait for another thread to end the pool manipulation - that would be data synchronization.
It needs to wait for another thread to give a connection back to the pool, which is a different thing.
Mutual exclusion is most often **not** the right way to implement control synchronization.

See Chapter 2 of https://www.oreilly.com/library/view/concurrent-programming-on/9780321434821/[Joe Duffy, Concurrent Programming on Windows] for a discussion of data and control synchronization.

== Mutual exclusion and locks

In a broad sense, mutual exclusion aims to ensure that no more than one thread can simultaneously access the same data.
This is achieved by:

* Identifying all code blocks that access the shared data.
* Ensuring that the execution of any of those blocks requires the acquisition of the mutual exclusion object associated to the shared data.

A mutual exclusion object, also called _mutex_ or _lock_ has two states - _unlocked_ and _locked_ (by a specific thread) - and two operations - _acquire_ and _release_.

* An _acquire_ operation made by thread _T_ on an _unlocked_ _mutex_ will atomically transition the mutex to the _locked(T)_ state.  
* A _release_ operation on an _locked(T)_ _mutex_, performed by thread _T_ transitions the mutex to the _unlocked_ state.
    ** A _release_ operation on an _locked(T)_ _mutex_, performed by any thread other than _T_ will be considered an error.
* Any _acquire_ operation by thread _T1_ on a _locked(T2)_ _mutex_ waits until the _mutex_ transition to the _locked(T1)_.


Some locks have reentrant acquisition:

* _acquire_ operation on a lock acquired by the requesting thread does succeed, and a reentrancy counter is incremented.
* _release_ operation decrements the reentrancy counter. The lock only goes to the _unlocked_ state if the counter reaches zero.

Using locks for safely share mutable data between threads.

* Associate a lock *instance* to each shared data structure *instance*.
* _acquire_ the *associated* lock before entering *any* code block that accesses the data structure.
* _release_ the lock when leaving those those code blocks, both _normally_ or via an exception.
  
Mutual exclusion only works if *every* code block that accesses the shared data access follows this acquire-release protocol.
This requirement fits well into the encapsulation provided by the `class` construct.

* Make the thread shared data be private class fields.
* Make the lock also be a private class field.
* Operations over the shared data are exclusively done via public methods.
    ** These public methods ensure the lock protocol by acquiring the lock at the beginning and releasing it at the end.
    ** Private methods typically do not need to acquire the lock, since they cannot be called from the outside directly. 
* Make sure no references to internal mutable data are exposed via the public methods.
    ** An example would be a public method returning a iterator to an internal mutable list.

== Locks in the JVM

The Java language and JVM standard class library provides two type of locks:

* The `Lock` interface and the associated implementing classes.
* Intrinsic locks, where every object can act as a lock.

=== The `Lock` interface

The Java class library also provides the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/Lock.html[`Lock`] interface and some implementing classes, namely the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html[`ReentrantLock`] class.

Instances implementing the `Lock` interface are not used automatically by special language constructs.
Instead, they have `lock` and `unlock` methods that need to be explicitly used.
Special care needs to be taken to ensure that when a thread exits a lock-protected code block the lock is indeed released.
The Kotlin standard library provides te `Lock.withLock` function that receives another function and runs it in possession of the lock, ensuring the lock release at the end, event if an exception was thrown.

.The `withLock` function
[source, kotlin]
----
public inline fun <T> Lock.withLock(action: () -> T): T {
    contract { callsInPlace(action, InvocationKind.EXACTLY_ONCE) }
    lock()
    try {
        return action()
    } finally {
        unlock()
    }
}
----

=== Intrinsic locks

In java, every object has an associated lock, usually called the _intrinsic lock_.
This lock is acquired and release via the `synchronized` language construction, which has https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html[two forms].

==== Synchronized Statements

The Java language includes the `synchronized` statement.

.synchronized statements in Java
[source, java]
----
synchronized(theObjectWithTheIntrinsicLock) {
  // block executed while holding the theObjectWithTheIntrinsicLock lock
}
----

The Kotlin standard library for the JVM provides a `synchronized` function, which allows for a syntactically similar use. 

.synchronized inline function in Kotlin
[source, kotlin]
----
synchronized(theObjectWithTheIntrinsicLock) {
  // block executed while holding the theObjectWithTheIntrinsicLock lock
}
----

The signature for the `synchronized` Kotlin function is

.synchronized inline function in Kotlin
[source, kotlin]
----
inline fun <R> synchronized(lock: Any, block: () -> R): R
----

Note the that `synchronized` Kotlin function is only available when targeting the JVM platform and is not available for other Kotlin targets.

==== Synchronized Methods

The Java language also provides the `synchronized`` method modifier.

.synchronized methods in Java
[source, java]
----
public synchronized void someInstanceMethod(...) {
  // statements executed while holding the lock associated to the `this` object
}

public static synchronized void someStaticMethod(...) {
  // statements executed while holding the lock associated to the *Class* object
}
----

In Kotlin, the same behavior can be achieved via the `@Synchronized` special annotation

.synchronized methods in Kotlin
[source, kotlin]
----
@Synchronized
fun someInstanceMethod(...) {
  // statements executed while holding the lock associated to the `this` object
}

companion object {
    @Synchronized
    fun someStaticMethod(...) {
        // statements executed while holding the lock associated to the *Class* object
    }
}
----

Again, the `@Synchronized` is only available when targeting the JVM and is note available for other Kotlin language targets.

Note that objects implementing the `Lock` interface also have intrinsic locks, because in the JVM _any_ object has an intrinsic lock.
However they are **distinct** locks:
- The `synchronized(aLock)` statement acquires the intrinsic lock associated to `aLock` but not the `aLock` lock.
- The `aLock.lock()` statement acquires the `aLock` lock.

=== Locks and the memory model

Locks, both intrinsic and `Lock` based, also ensure correct memory actions visibility between threads.
As we will see in the Java Memory Model module, the lock acquisition by a thread ensures all subsequent reads on that thread _see_ the writes made by another thread before it released the lock.

----
Thread 0                  Thread 1
========                  ========
a = 1
b = 2
lock.unlock()

                          lock.lock()
                          var l1 = a // "sees" the `a = 1` write
                          var l2 = b // "sees" the `b = 2` write           
----

Without the `lock.lock()` performed on `Thread 1`, there is no assurance the reads of `a` and `b` will see the values written by `Thread 0`.

=== Locks and class invariants

A class invariant is a condition over the classe's fields.
For instance, a circular double-linked list may have the invariant that all nodes have non-null `next` and `previous` fields.

The class methods:

* *May assume* the invariant to be true when they begin execution.
* *Must ensure* the invariant to be true when end execution.

However, inside a method execution, the invariants don't have to be ensured (i.e. the objects may be in inconsistent states)
For instance, while inserting a new node, it is acceptable for the node's `next` field to be assigned while the `previous` is still null.
This is acceptable as long as this inconsistent state is transient and not observable by other methods.
On a single-threaded model, this is indeed true because method execution is serialized: a method cannot observe the data structure while another method is mutating it and it is in an inconsistent state.

However, on multi-thread models, this is no longer true by default.
The use of locks is a way to recover this property:
- Methods *may assume* the invariant to be true after acquiring the lock.
- Methods *must ensure* the invariant to be true before they release the lock.

=== Locks and busy waiting

When using locks to implement data synchronization, it is expected that threads will hold on the locks for very small amounts of time: the minimum necessary to observe and/or mutate data structures.
Due to this, lock implementations on multi-processor systems typically don't transition a thread to the non-ready state when it tries to acquired a locked lock. 
The rationale is that the thread owning the lock is running in another processor and will soon release it.
So, in a rather simplified way, the acquiring thread just keeps polling on the lock state until it becomes unlocked.
This is called busy waiting.
Typically, lock implementation don't do this busy waiting indefinitely, as will switch to non-busy waiting after a small time period.
